### ISSUE TITLE
Reproducing Procgen results

### ISSUE THREAD

**Issue by symoon11** [rraileanu/idaac#4]
Hi. @rraileanu

Thank you for your interesting work on RL generalization.

I am trying to reproduce your Procgen results using the same hyperparameter setting across the environments, following Appendix C in your paper, but get scores lower than reported in some environments (Plunder, ...).

Should I use environment-specific hyperparameter settings to reproduce the results?

**Comment by rraileanu** [comment]
Hi and thanks for your question! 

In order to reproduce the results in the paper, you need to use the flag --use_best_hps, which will use different HPs for the different games according to best_hyperparameters.py. The default code uses the same set of HPs for all environments, which are the best ones overall.

Let me know if you have any other questions.

**Comment by symoon11** [comment]
Thank you for the clarification, but the scores still have high variances.

In my understanding, the paper trains 10 policies with different random seeds and evaluates the average return of each policy on 10 test episodes. The mean and standard deviation are then computed over the random seeds. Is it correct?

I would greatly appreciate your feedback.

**Comment by rraileanu** [comment]
Yes, that is correct, and indeed, the variance can be quite high on some environments. We also use smoothing to make the plots more readable.
